In [ ]:
# 导入 numpy 库，并使用 np 作为别名
import numpy as np

# 打印已安装的 numpy 版本号
print(f"NumPy Version: {np.__version__}")
# 输出示例: NumPy Version: 2.3.4

## 1. ndarray

### 1.1 从`Python`序列创建

- `np.array(object, dtype=None)`: 将`Python`的列表(`list`)或元组(`tuple`)直接转换为`NumPy`数组.

In [ ]:
# 1. 从 Python 列表创建一维数组
list_1d = [1, 2, 3, 4, 5]
arr_1d = np.array(list_1d)
print(f"一维数组: \n{arr_1d}")
# 一维数组: 
# [1 2 3 4 5]

# 2. 从嵌套列表创建二维数组 (矩阵)
list_2d = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(list_2d)
print(f"二维数组: \n{arr_2d}")
# 二维数组: 
# [[1 2 3]
#  [4 5 6]]

# 3. 创建时指定数据类型为浮点数
arr_float = np.array([1, 2, 3], dtype=np.float64)
print(f"指定数据类型的数组: \n{arr_float}")
# 指定数据类型的数组: 
# [1. 2. 3.]

### 1.2 依据规则创建：arange, linspace

- `np.arange([start, ]stop, [step, ], dtype=None)`: 创建一个等差序列，类似于 Python 的 range() 函数，但返回的是 NumPy 数组，并且支持浮点数步长。
- `np.linspace(start, stop, num=50, endpoint=True)`: 在指定的区间内，创建一个包含指定数量元素的等间隔序列。这在科学绘图或数据采样时非常有用。

In [ ]:
# 1. 使用 arange 创建 0 到 9 的整数数组
arr_range = np.arange(10)
print(f"arange(10): {arr_range}")
# arange(10): [0 1 2 3 4 5 6 7 8 9]

# 2. 使用 arange 创建从 2 到 10，步长为 2 的数组
arr_step = np.arange(2, 11, 2)
print(f"arange(2, 11, 2): {arr_step}")
# arange(2, 11, 2): [ 2  4  6  8 10]

# 3. 使用 linspace 在 0 和 1 之间创建 5 个等间隔的点
arr_linspace = np.linspace(0, 1, 5)
print(f"linspace(0, 1, 5): {arr_linspace}")
# linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]

### 1.3 创建标准形态数组：zeros, ones, eye, full

- `np.zeros(shape, dtype=float)`: 创建一个指定形状 shape 且所有元素都为 0 的数组。
- `np.ones(shape, dtype=float)`: 创建一个指定形状 shape 且所有元素都为 1 的数组。
- `np.full(shape, fill_value, dtype=None)`: 创建一个指定形状 shape 且所有元素都为 fill_value 的数组。
- `np.eye(N, M=None)`: 创建一个 N×M 的单位矩阵（主对角线为 1，其余为 0）。如果 M 为 None，则默认为 N×N。

In [ ]:
# 1. 创建一个 2 行 3 列的全零矩阵
arr_zeros = np.zeros((2, 3))
print(f"2x3 全零矩阵: \n{arr_zeros}")
# 2x3 全零矩阵: 
# [[0. 0. 0.]
#  [0. 0. 0.]]

# 2. 创建一个长度为 5 的全一向量 (一维数组)
arr_ones = np.ones(5)
print(f"长度为 5 的全一向量: \n{arr_ones}")
# 长度为 5 的全一向量: 
# [1. 1. 1. 1. 1.]

# 3. 创建一个 3x3，所有元素都为 7 的矩阵
arr_full = np.full((3, 3), 7)
print(f"3x3 全 7 矩阵: \n{arr_full}")
# 3x3 全 7 矩阵: 
# [[7 7 7]
#  [7 7 7]
#  [7 7 7]]

# 4. 创建一个 4x4 的单位矩阵
arr_eye = np.eye(4)
print(f"4x4 单位矩阵: \n{arr_eye}")
# 4x4 单位矩阵: 
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]

### 1.4 创建随机数据：np.random 模块

- `np.random.rand(d0, d1, ...)`: 创建一个或多个维度的数组，其元素是在 [0, 1) 区间内均匀分布的随机数。
- `np.random.randn(d0, d1, ...)`: 创建一个或多个维度的数组，其元素是符合标准正态分布（均值为0，方差为1）的随机数。
- `np.random.randint(low, high=None, size=None)`: 创建一个指定大小 size 的数组，其元素是在 [low, high) 区间内的随机整数。

In [ ]:
# 为了让随机结果可复现，通常会设置一个随机种子
np.random.seed(42)

# 1. 创建一个 2x3 的数组，元素在 [0, 1) 之间均匀分布
arr_rand = np.random.rand(2, 3)
print(f"2x3 均匀分布随机数组: \n{arr_rand}")
# 2x3 均匀分布随机数组: 
# [[0.37454012 0.95071431 0.73199394]
#  [0.59865848 0.15601864 0.15599452]]

# 2. 创建一个 3x3 的数组，元素符合标准正态分布
arr_randn = np.random.randn(3, 3)
print(f"3x3 标准正态分布随机数组: \n{arr_randn}")
# 3x3 标准正态分布随机数组: 
# [[-0.63004838  0.68658932 -1.1664182 ]
#  [ 0.52219328 -1.26875326  0.42111327]
#  [-0.23413696  1.57921282  0.76743473]]

# 3. 创建一个包含 10 个元素的数组，元素为 [1, 101) 之间的随机整数
arr_randint = np.random.randint(1, 101, size=10)
print(f"10 个 [1, 101) 范围内的随机整数: \n{arr_randint}")
# 10 个 [1, 101) 范围内的随机整数: 
# [82 15 76 17 83 78 98 40 18 10]

## 2. 属性探查和形状变换
快速了解其内部结构（如维度、形状、数据类型），并根据需要灵活地改变其形状。

### 2.1 数组的核心属性：shape, dtype, ndim, size

这些属性是 `ndarray` 对象自带的元数据，无需计算即可快速访问，帮助我们理解数组的“骨架”。

- `ndarray.ndim`: 数组的维度数量（轴的个数）。
- `ndarray.shape`: 一个元组，表示数组在每个维度上的大小。
- `ndarray.size`: 数组中元素的总数量，等于 shape 中各元素之积。
- `ndarray.dtype`: 描述数组中元素类型的对象。

In [15]:
# 创建一个 2 行 3 列 4 深度的三维数组
arr_3d = np.arange(24).reshape((2, 3, 4))
print(f"示例三维数组: \n{arr_3d}\n")

# 探查其核心属性
print(f"维度数量 (ndim): {arr_3d.ndim}")
# 维度数量 (ndim): 3

print(f"形状 (shape): {arr_3d.shape}")
# 形状 (shape): (2, 3, 4)

print(f"元素总数 (size): {arr_3d.size}")
# 元素总数 (size): 24

print(f"数据类型 (dtype): {arr_3d.dtype}")
# 数据类型 (dtype): int64 (具体位数可能因系统而异)

示例三维数组: 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

维度数量 (ndim): 3
形状 (shape): (2, 3, 4)
元素总数 (size): 24
数据类型 (dtype): int64
